USE WareHouseManagementSystem;

CREATE TABLE Product(
    productId INT NOT NULL,
    title VARCHAR(50) NOT NULL,
    summary TEXT NULL DEFAULT NULL,
    productType INT NOT NULL DEFAULT 0,
    content TEXT NULL DEFAULT NULL,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(productId)
    );